"""Run Figure 4: on-policy conversation generated by the evaluated model."""
from pathlib import Path
import argparse,json
from figure_common import fit_probe,generate_on_policy,json_input,margin_summary,plot_margin_panels,prepare,questions,score_prefixes
from run_experiment import conversation_messages,resolve
def main():
    p=argparse.ArgumentParser(); p.add_argument("--config",type=Path,default=Path("figures/figure4/config.yaml")); a=p.parse_args(); cfg,b=prepare(a.config)
    prompts=json_input(cfg,"user_prompts")["user_prompts"]; turns=generate_on_policy(b,prompts,int(cfg["generation"]["max_new_tokens"])); generic=questions(cfg,"generic_questions",{"train","validation"}); target=questions(cfg,"target_questions",{"test"}); full=conversation_messages(turns,len(turns)); layer,probe,_=fit_probe(b,cfg,generic,True,[full]); prefixes=[(i,conversation_messages(turns,i)) for i in range(len(turns)+1)]; scores=score_prefixes(b,cfg,probe,layer,[("Generic",generic[generic.split=="validation"]),("Context-relevant",target)],prefixes); out=resolve(cfg["_base"],cfg["experiment"]["output_dir"]); out.mkdir(parents=True,exist_ok=True); (out/"generated_conversation.json").write_text(json.dumps({"turns":turns},indent=2),encoding="utf-8"); scores.to_csv(out/"scores.csv",index=False); plot_margin_panels([("On-policy consciousness",margin_summary(scores,cfg))],out/"figure4.png",caption="What this shows: whether the same model that generates the conversation also changes its internal factuality separation over successive turns. Context-relevant values below zero indicate an inversion; generic values provide a stability control."); print(f"Figure 4 saved to {out}")
if __name__=="__main__": main()
